# 📚 BROKER

def test():
    return 'this is BROKER test.'


from BROKER_BINDS import BROKER_BINDS
from BROKER_CREDENTIALS import BROKER_CREDENTIALS
from BROKER_PAY import BROKER_PAY
from BROKER_PROMPT import BROKER_PROMPT
from BROKER_SESSIONS import BROKER_SESSIONS
from BROKER_SETUP import BROKER_SETUP
from BROKER_SHARE import BROKER_SHARE


# ✅ DONE
class BROKER(BROKER_BINDS, BROKER_CREDENTIALS, BROKER_PAY, BROKER_PROMPT, BROKER_SESSIONS, BROKER_SETUP, BROKER_SHARE):
    ''' 🤵 https://quip.com/SJadAQ8syGP0/-Broker '''
    pass

    